services:
  murmur:
    build: .
    ports:
      - "64738:64738"
      - "64738:64738/udp"
    restart: always
    volumes:
      - ./murmur.sqlite:/data/mumble-server.sqlite
      - ./murmur.ini:/etc/murmur.ini
    environment:
      - MUMBLE_CUSTOM_CONFIG_FILE=/etc/murmur.ini
    networks:
      - podcast-net

  mumo:
    build: ./bots/mumo
    restart: always
    volumes:
      - ./bots/mumo:/data
    depends_on:
      - murmur
    networks:
      - podcast-net

  bots-legacy:
    build: ./bots
    depends_on:
      - murmur
    restart: always
    volumes:
      - ./recordings:/bots/recordings
    networks:
      - podcast-net

networks:
  podcast-net:
    driver: bridge
