# Murmur configuration file.

# Welcometext sent to clients when they connect.
welcometext="Welcome to the FT Podcast Murmur Server!"

# Port to bind TCP and UDP sockets to.
port=64738

# Password to join server.
serverpassword=

# Maximum bandwidth (in bits per second) clients are allowed
# to send speech at.
bandwidth=130000

# Maximum number of concurrent clients allowed.
users=100

# Regular expression used to validate channel names.
# (Note: this is a PCRE regular expression)
channelname=[ \\-=\\w\\#\\[\\]\\{\\}\\(\\)\\@\\|]+

# Regular expression used to validate user names.
# (Note: this is a PCRE regular expression)
username=[-=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.]+

# Allow clients to use HTML in messages, user comments and channel descriptions?
allowhtml=true

# Log to standard output
logfile=

# SSL
# sslCert=
# sslKey=

# Bonjour: Enable announcement of the server on the LAN
bonjour=true
