url: localhost
name: Bot
keyFile: "./mumble-bot/bot.key"
certFile: "./mumble-bot/bot.cert"
channel: "🎙️ Stage 🔴"
audioCacheAmount: 150 # Amount of audios to cache
port: 8080 # Port to run the webinterface on
dbName: botdb # Name of the database
dbPassword: botdb # Password to connect tot eh database
tmpDir: ./mumble-bot/temp # Directory to store cached audios and temporary files in
soundsDir: ./sounds # Directory to store sounds in
language: english # One of Postgres' text search languages

