stages:
  - build
  - test

variables:
  POSTGRES_DB: bot-test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: "postgres"
  POSTGRES_HOST_AUTH_METHOD: "trust"
  MUMBLE_URL: dcshock-docker-mumble-server
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH

buildimage:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/buildimage:latest
  when: manual

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

integration-test:
  services:
    - postgres:latest
    - dcshock/docker-mumble-server:latest
  image: $CI_REGISTRY_IMAGE/buildimage:latest
  script:
    - make integration-test
  stage: test
  artifacts:
    when: always
    paths:
      - jest-screenshot-report/
  allow_failure: true

test:
  services:
    - postgres:latest
  image: $CI_REGISTRY_IMAGE/buildimage:latest
  script:
    - make test
  stage: test
  artifacts:
    when: always
    paths:
      - coverage/
  allow_failure: true

lint:
  image: $CI_REGISTRY_IMAGE/buildimage:latest
  script:
    - make lint
  stage: test

build:
  image: $CI_REGISTRY_IMAGE/buildimage:latest
  script:
    - make release
  stage: build
  artifacts:
    paths:
      - dist/
      - server/
      - src/
      - package.json
      - yarn.lock
      - typings/
      - README.md